### ISSUE TITLE
Do you support managed elasticsearch operations?

### ISSUE THREAD

**Issue by pit** [yandex-cloud/python-sdk#20]

**Comment by pit** [comment]
I see you have elasticsearch classes in repo, but don't have them in _sdk.py file. Is it a bug and I can send PR or it's not tested etc?

I was testing this part with this code:
```
#!/usr/bin/env python3
import yandexcloud
from yandex.cloud.mdb.elasticsearch.v1.cluster_service_pb2 import GetClusterRequest
from yandex.cloud.mdb.elasticsearch.v1.cluster_service_pb2_grpc import ClusterServiceStub

cloud_id = "..."
folder_id = "..."
sdk = yandexcloud.SDK(token="...")
zuko = sdk.client(ClusterServiceStub).Get(GetClusterRequest(cluster_id="..."))
print(zuko)
```

This code produces following error:
```
python3 /tmp/test-yac-es.py
Traceback (most recent call last):
  File "/tmp/test-yac-es.py", line 25, in <module>
    test()
  File "/tmp/test-yac-es.py", line 21, in test
    zuko = sdk.client(ClusterServiceStub).Get(GetClusterRequest(cluster_id="..."))
  File "/usr/local/lib/python3.8/site-packages/yandexcloud/_sdk.py", line 29, in client
    service = _service_for_ctor(stub_ctor)
  File "/usr/local/lib/python3.8/site-packages/yandexcloud/_sdk.py", line 73, in _service_for_ctor
    raise RuntimeError('Unknown service {}'.format(stub_ctor))
RuntimeError: Unknown service <class 'yandex.cloud.mdb.elasticsearch.v1.cluster_service_pb2_grpc.ClusterServiceStub'>
```
