### ISSUE TITLE
apploadbalancer service is not supported

### ISSUE THREAD

**Issue by AlexeyMinasyan** [yandex-cloud/python-sdk#37]
Trying to set up apploadbalancer service, but it doesn't seem to work. To compare, similar configuration works fine classic (network) load balancer

Code
```
import yandexcloud
from yandex.cloud.apploadbalancer.v1.load_balancer_service_pb2_grpc import LoadBalancerServiceStub

sdk = yandexcloud.SDK(token=token)
load_balancer_service = sdk.client(LoadBalancerServiceStub)
````

Error
```
>>> load_balancer_service = sdk.client(LoadBalancerServiceStub)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aminasian/.pyenv/versions/yc_scheduler/lib/python3.8/site-packages/yandexcloud/_sdk.py", line 42, in client
    service = _service_for_ctor(stub_ctor)
  File "/Users/aminasian/.pyenv/versions/yc_scheduler/lib/python3.8/site-packages/yandexcloud/_sdk.py", line 86, in _service_for_ctor
    raise RuntimeError('Unknown service {}'.format(stub_ctor))
RuntimeError: Unknown service <class 'yandex.cloud.apploadbalancer.v1.load_balancer_service_pb2_grpc.LoadBalancerServiceStub'>
```

Environment
* yandexcloud version is 0.130.0
* Python 3.8.12 (default, Sep 29 2021, 16:13:33) 
  [Clang 12.0.5 (clang-1205.0.22.9)] on darwin

**Comment by l0kix2** [comment]
Released in 0.131
